version: '3.5'

networks:
  localdev:
    name: localdev
    
services:
  main-api:
    build: #Tweetbook/
        context: .
        dockerfile: Tweetbook/Dockerfile
    restart: always
    ports:
      - "7000:80"
    depends_on:
      - db-server
      - redis
    networks:
      - localdev
        
  db-server:
    image: mcr.microsoft.com/mssql/server
    container_name: db-server
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Tommy1234
      - MSSQL_TCP_PORT=1433
    ports:
      - "1400:1433"
    networks:
      - localdev
  
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - localdev